name: shell_command_generator_example
description: Example app for shell_command_generator
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  shell_command_generator_annotation:

dev_dependencies:
  shell_command_generator:
