name: shell_command_generator
description: Run shell commands as part of your build process.
version: 0.2.0
homepage: https://github.com/tjarvstrand/shell_command_generator

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  analyzer: ^7.0.0
  build: ^2.4.1
  shell_command_generator_annotation: ^0.2.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.14
  build_test: ^2.2.3
  dart_style: ^3.0.1
  lints: ^5.0.0
  pub_semver: ^2.2.0
  test: ^1.24.0
